config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def new
  #   @list = List.find(params[:list_id])
  #   @bookmark = Bookmark.new
  # end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%# <h1>Add a new movie</h1> %>

<!--%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Add movie", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/384a3f7d08.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="/lists">
          <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Home-icon.svg/1200px-Home-icon.svg.png"/>
        </a>
        <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> %>

        <div class="" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item dropdown">
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/VisualEditor_-_Icon_-_Menu.svg/1024px-VisualEditor_-_Icon_-_Menu.svg.png" />
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/lists/new">Add a new list</a>
                  <%# <a class="dropdown-item" href="#"></a> %>
                </div>
              </li>
              <!--li class="nav-item"-->
              <!--/li-->
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1585647347384-2593bc35786b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80);">
  <div class="container">
    <h1>Movie saver</h1>
    <p>Keep track of your favorites</p>
  </div>
</div>

<% def_img = 'https://www.twosisterscrafting.com/wp-content/uploads/2016/01/perfect-stovetop-popcorn-1200-featured-735x735.jpg' %>

<div class="container">
  <h3 class="mt-5">My Lists</h3>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="card-category col-sm m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
                  url('<%= list.photo.attached? ? cl_image_path(list.photo.key) : def_img %>')">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

<div class="btn-container">
  <%= link_to "Create a list", new_list_path, class: "btn btn-outline-danger mt-5" %>
</div>

<!-- https://www.twosisterscrafting.com/wp-content/uploads/2016/01/perfect-stovetop-popcorn-1200-featured-735x735.jpg -->

app/views/lists/new.html.erb
<h1 class='text-center my-4'>Add a new list</h1>

<div class='container'>
  <div class='row d-flex justify-content-center'>
    <div class='col-sm-6'>
      <%= simple_form_for [ @list ] do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Add list", class: "btn btn-outline-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<% def_img = 'https://www.twosisterscrafting.com/wp-content/uploads/2016/01/perfect-stovetop-popcorn-1200-featured-735x735.jpg' %>

<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : def_img %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-trip col-sm m-3">
        <img src="<%= bookmark.movie.poster_url %>"/>
        <div class="card-trip-infos">
          <div class="mb-3">
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.movie.overview %></p>
          </div>
        </div>
        <div class="comment">
          <i class="fa-solid fa-quote-left"></i>
          <p><em><%= bookmark.comment %></em></p>
        </div>
        <h2 class="card-trip-pricing">
          <%= link_to bookmark_path(bookmark), method: :delete do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

<h3 class="text-center my-4">Add a movie</h3>
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-6">
      <%= simple_form_for [ @list, @bookmark ] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.submit "Add movie", class: "btn btn-outline-danger mb-4" %>
      <% end %>
    </div>
  </div>
</div>